// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUC5DIdMz0eOp2KClcHZH5ZjJP-meb2sk',
    appId: '1:483990931530:web:af934c4af768d68f0afeb3',
    messagingSenderId: '483990931530',
    projectId: 'lifter-aa6fb',
    authDomain: 'lifter-aa6fb.firebaseapp.com',
    storageBucket: 'lifter-aa6fb.appspot.com',
    measurementId: 'G-05C4WPGFMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTVz0EIHNRJThtz9_EOIIM-5-tyGwOMMo',
    appId: '1:483990931530:android:e960c24ff861e7440afeb3',
    messagingSenderId: '483990931530',
    projectId: 'lifter-aa6fb',
    storageBucket: 'lifter-aa6fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7p5lIci8qEsv91rDnvEIniyW5Y3oFWD0',
    appId: '1:483990931530:ios:85833179c64223f30afeb3',
    messagingSenderId: '483990931530',
    projectId: 'lifter-aa6fb',
    storageBucket: 'lifter-aa6fb.appspot.com',
    iosClientId: '483990931530-kkel57i784khjp6hijp76n9aefmkas3b.apps.googleusercontent.com',
    iosBundleId: 'dk.michaelguldborg.lifter',
  );
}
